name: .NET 6.0

on:
  push:
    branches: [ master, net6 ]

jobs:
  build:
    name: Test on .NET ${{ matrix.dotnet }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet: [ '6.0.408' ]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build
